//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendAccountManagement.Web.Resources.Views.AccountManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApprovedPersonRoleChange {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApprovedPersonRoleChange() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrontendAccountManagement.Web.Resources.Views.AccountManagement.ApprovedPersonRol" +
                            "eChange", typeof(ApprovedPersonRoleChange).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Secretary.
        /// </summary>
        internal static string CompanySecretaryCompanyRole {
            get {
                return ResourceManager.GetString("CompanySecretaryCompanyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        internal static string DirectorCompanyRole {
            get {
                return ResourceManager.GetString("DirectorCompanyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Company Role.
        /// </summary>
        internal static string EditCompanyRoleDetailsTitle {
            get {
                return ResourceManager.GetString("EditCompanyRoleDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a role.
        /// </summary>
        internal static string InvalidSelection {
            get {
                return ResourceManager.GetString("InvalidSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member of a limited liability partnership.
        /// </summary>
        internal static string MemberOfALimitedLiabilityPartnershipCompanyRole {
            get {
                return ResourceManager.GetString("MemberOfALimitedLiabilityPartnershipCompanyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        internal static string PartnerCompanyRole {
            get {
                return ResourceManager.GetString("PartnerCompanyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your role in the organisation, as shown on Companies House?.
        /// </summary>
        internal static string WhatIsYourRoleInCompaniesHouse {
            get {
                return ResourceManager.GetString("WhatIsYourRoleInCompaniesHouse", resourceCulture);
            }
        }
    }
}
