//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendAccountManagement.Web.Resources.Views.AccountManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UkNation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UkNation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrontendAccountManagement.Web.Resources.Views.AccountManagement.UkNation", typeof(UkNation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select where in the UK your organisation is based.
        /// </summary>
        public static string UkNation_ErrorMessage {
            get {
                return ResourceManager.GetString("UkNation.ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For non-UK organisations this should be one of the following:.
        /// </summary>
        public static string UkNation_ForNonUkOrganisations {
            get {
                return ResourceManager.GetString("UkNation.ForNonUkOrganisations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For UK organisations this should be:.
        /// </summary>
        public static string UkNation_ForUkOrganisations {
            get {
                return ResourceManager.GetString("UkNation.ForUkOrganisations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your principal place of business.
        /// </summary>
        public static string UkNation_PrincipalPlaceOfBusiness {
            get {
                return ResourceManager.GetString("UkNation.PrincipalPlaceOfBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your principal place of business (if you’re not registered).
        /// </summary>
        public static string UkNation_PrincipalPlaceOfBusinessIfNotRegistered {
            get {
                return ResourceManager.GetString("UkNation.PrincipalPlaceOfBusinessIfNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your UK nation.
        /// </summary>
        public static string UkNation_Title {
            get {
                return ResourceManager.GetString("UkNation.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to know which UK nation you’re based in..
        /// </summary>
        public static string UkNation_WeNeedToKnow {
            get {
                return ResourceManager.GetString("UkNation.WeNeedToKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where in the UK is your business based?.
        /// </summary>
        public static string UkNation_WhereInTheIsYourUKBusinessBased {
            get {
                return ResourceManager.GetString("UkNation.WhereInTheIsYourUKBusinessBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where your head office is.
        /// </summary>
        public static string UkNation_WhereYourHeadOfficeIs {
            get {
                return ResourceManager.GetString("UkNation.WhereYourHeadOfficeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where your organisation is registered.
        /// </summary>
        public static string UkNation_WhereYourOrganisationIsRegistered {
            get {
                return ResourceManager.GetString("UkNation.WhereYourOrganisationIsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where your UK branch or UK postal address is.
        /// </summary>
        public static string UkNation_WhereYourUKBranchIs {
            get {
                return ResourceManager.GetString("UkNation.WhereYourUKBranchIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your UK nation.
        /// </summary>
        public static string UkNation_YourUKNation {
            get {
                return ResourceManager.GetString("UkNation.YourUKNation", resourceCulture);
            }
        }
    }
}
