trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - 'src/*'

pool: DEFRA-COMMON-ubuntu2004-SSV3

variables:
  - template: vars/DEV4-development.yaml
  - name: solutionFolder
    value: src
  - name: projectFolder
    value: FrontendAccountManagement.Web
  - name: testProjectFolder
    value: FrontendAccountManagement.Web.UnitTests
  - name: sonarQubeProjectKey
    value: frontend-accountmanagement-microservice
  - name: sonarQubeProjectName
    value: frontend-accountmanagement-microservice
  - name: runNugetTasks
    value: true
  - name: runTests
    value: true
  - name: dotnetVersion
    value: dotnetVersion8

resources:
  repositories:
    - repository: CommonTemplates
      name: RWD-CPR-EPR4P-ADO/epr-webapps-code-deploy-templates
      type: git
      ref: feature/automation-testing-facade
    
    - repository: AutomationTesting
      name: RWD-CPR-EPR4P-ADO/epr-playwright-bdd
      type: git
      ref: develop-template-fix

stages:
- template: epr-build-pipeline.yaml@CommonTemplates
  parameters:
    solutionFolder: ${{ variables.solutionFolder }}
    projectFolder: ${{ variables.projectFolder }}
    testProjectFolder: ${{ variables.testProjectFolder }}
    sonarQubeProjectKey: ${{ variables.sonarQubeProjectKey }}
    sonarQubeProjectName: ${{ variables.sonarQubeProjectName }}
    runTests: ${{variables.runTests}}
    azureSubscription: $(azureSubscription)
    acrAzureContainerRegistryName: $(acr.azureContainerRegistryName)
    acrRepositoryName: $(acr.repositoryName)
    branchName: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), '/', '_') }}
    runNugetTasks: ${{ variables.runNugetTasks }}
    serviceName: $(serviceName)
    dotnetVersion: ${{ variables.dotnetVersion }}

- template: templates/stage-deploy-template.yaml
